### PR TITLE
fix msbuild being used on mono < 5.0.0.0 instead of xbuild

### LINKED ISSUE #1539: Using msbuild over xbuild causes issues ( at least on Mono 4.8.x)
cc @baronfel 

Recent FAKE (> 4.53.0?)  has caused a regression on Linux/macOS with Mono 4.8 and Mono latest (currently 4.8.1).  It invokes MSBuild instead of XBuild on these platforms ([this PR](https://github.com/fsharp/FAKE/pull/1488#issuecomment-298158602)).

That's fine, but I believe MSBuild on Unix/Mono has problems, at least before Mono 5.0.0 (yet to be released).  For example, when compiling FSharp.Compiler.Service with (latest FAKE and FSharp.,Compiler.Tools](https://travis-ci.org/fsharp/FSharp.Compiler.Service/jobs/227043065) using this:

```
  /Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild  /Users/travis/build/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.sln /t:Build    /p:RestorePackages="False" /p:Configuration="Release" /p:TargetFrameworkVersion="v4.5" /logger:Fake.MsBuildLogger+ErrorLogger,"/Users/travis/build/fsharp/FSharp.Compiler.Service/packages/FAKE/tools/FakeLib.dll"
```

I get

```
/Users/travis/build/fsharp/FSharp.Compiler.Service/packages/FSharp.Compiler.Tools/tools/Microsoft.FSharp.Targets(125,13): 
error MSB4131: The "ResourceFilesWithManifestResourceNames" parameter is not supported by 
the "CreateFSharpManifestResourceName" task. Verify the parameter exists on the task, and it 
is a gettable public instance property. 
[/Users/travis/build/fsharp/FSharp.Compiler.Service/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
```

This seems to be an MSBuild on Unix and Mono issue.

I suspect we should be avoiding defaulting to MSBuild on Unix, at least on Mono 4.8.x and before.  I've yet to validate if this issue goes away on Mono 5.0.0.

### Repro steps

Consider [this PR](https://github.com/fsharp/FSharp.Compiler.Service/pull/765).  

* [this commit fails to build](https://github.com/fsharp/FSharp.Compiler.Service/pull/765/commits/4d5fa48fba6eda790fdbe65914c22ac9af4571ce).  It uses latest FAKE and invokes ``msbuild`` on Unix

* I'm in the process of validating that [this commit succeeds](https://github.com/fsharp/FSharp.Compiler.Service/pull/765/commits/85d3f960ba5c177a0706f2b3fc55cb59b5d52914).  It uses FAKE 4.53.0 instead of FAKE 4.60.0 and invokes ``xbuild`` on Unix

### Known workarounds

Use FAKE 4.53.0 or before (I'm in the process of validating this)
Perhaps use Mono 5.0.0 (?)

### Related information 

* Unix, Mono 4.8.*

### PR DESCRIPTION
**Pull request by baronfel**
Fixes #1539 by having the msbuild detection logic learn about mono versions.

For all branches we added the ability for the MSBuild environment variable to specify just a tool, which would then be searched for on the current PATH.

For mono >= 5.0.0.0 we default to msbuild on all path lookups, etc
For mono < 5.0.0.0 we default to xbuild for all similar lookups.

In addition I thought it would be a good chance to make the default msbuild functions pass through the number of cores on the machine in order to trigger parallel msbuild behavior.

### CODE REVIEW

File: src/app/FakeLib/MSBuildHelper.fs [hunk 1]
```diff
@@ -45,39 +45,56 @@ let toDict items =
...
+    | true, Some(_, Some(version)) when version > monoVersionToUseMSBuildOn -> 
+        let sources = [
+            msbuildEnvironVar |> Option.map (exactPathOrBinaryOnPath "msbuild")
+            msbuildEnvironVar |> Option.bind which
             which "msbuild"
             which "xbuild"
         ]
-        defaultArg (unixSources |> List.choose id |> List.tryHead) "xbuild"
-    else
+        defaultArg (sources |> List.choose id |> List.tryHead) "xbuild"
```
Comment (matthid) [inline src/app/FakeLib/MSBuildHelper.fs]: Should we use `msbuild` here?

File: src/app/FakeLib/MSBuildHelper.fs [hunk 2]
```diff
@@ -45,39 +45,56 @@ let toDict items =
...
     let which tool = ProcessHelper.tryFindFileOnPath tool
-    let environVarDir = EnvironmentHelper.environVarOrNone "MSBuild"
+    let msbuildEnvironVar = EnvironmentHelper.environVarOrNone "MSBuild"
 
-    if isUnix
-    then
-        let unixSources = [
-            environVarDir |> Option.map (exactPathOrBinaryOnPath "msbuild")
+    match isUnix, EnvironmentHelper.monoVersion with
+    | true, Some(_, Some(version)) when version > monoVersionToUseMSBuildOn ->
```
Comment (matthid) [inline src/app/FakeLib/MSBuildHelper.fs]: maybe even `>=` but I don't think it matters

File: src/app/FakeLib/MSBuildHelper.fs [hunk 3]
```diff
@@ -446,7 +464,10 @@ let MSBuildWithProjectProperties outputPath (targets : string) (properties : (st
             |> Set.unionMany
 
     let setBuildParam project projectParams =
-        { projectParams with Targets = targets |> split ';' |> List.filter ((<>) ""); Properties = projectParams.Properties @ properties project }
+        { projectParams with 
+            Targets = targets |> split ';' |> List.filter ((<>) "")
+            Properties = projectParams.Properties @ properties project
+            MaxCpuCount = Some ( Some (EnvironmentHelper.getMachineEnvironment().ProcessorCount)) }
```
Comment (matthid) [inline src/app/FakeLib/MSBuildHelper.fs]: I think its ok. But doesn't `msbuild` figure this out when no argument is given?

**Comment by baronfel** [comment]
@matthid good catches on both counts, thanks!

File: src/app/FakeLib/MSBuildHelper.fs (hunk 3 above)
Comment (baronfel) [inline src/app/FakeLib/MSBuildHelper.fs]: I noticed that the FAKE build itself, which uses `MSBuildWithDefaults` doesn't build with multiple cores because the CPU Count isn't provided on this very flow.

Comment (baronfel) [inline src/app/FakeLib/MSBuildHelper.fs]: in fact, none of the `MSBuildXXXX` helpers set the core count, so they fall prey to this. The only way to get around it is to use raw `build setParams` yourself.

Comment (matthid) [inline src/app/FakeLib/MSBuildHelper.fs]: @baronfel To be honest I don't think we should do such changes in FAKE 4 anymore. But I guess @forki probably has a different opinion on this. If it breaks somebody we will move this to FAKE 5 anyways :)

Comment (matthid) [inline src/app/FakeLib/MSBuildHelper.fs]: I'll leave it up to you :)

**Comment by baronfel** [comment]
That's fair. I've removed the CPU change.

**Comment by matthid** [comment]
https://travis-ci.org/fsharp/FAKE/builds/227224324#L6135 Good that we can get away from mono soon :)

**Comment by forki** [comment]
thanks for fixing this.

**Comment by nosami** [comment]
LGTM
