### PR TITLE
Fix #992 test failure when space in temp path.

### LINKED ISSUE #992: Build error locally
Just cloned the master repo on Windows and ran `build.cmd`. The build fails with the following exception:

```
Failures:                                                                     
                                                                              
compile csfiles to dll                                                        
» should compile to dll (FAIL)                                                
Fake.MSBuildHelper+BuildException: Exception of type 'Fake.MSBuildHelper+Build
Exception' was thrown.                                                        
   at Fake.CscHelper.Csc(FSharpFunc`2 setParams, FSharpList`1 inputFiles) in C
:\Dev\git\FAKE\src\app\FakeLib\CscHelper.fs:line 125                          
   at Test.FAKECore.compile_csfiles_to_dll.<>c.<.ctor>b__8_2() in C:\Dev\git\F
AKE\src\test\Test.FAKECore\CscSpecs.cs:line 60                                
                                                                              
Contexts: 250, Specifications: 670, Time: 23.77 seconds                       
  666 passed, 1 failed, 3 ignored                                             
Running build failed.                                                         
Error:                                                                        
System.Exception: MSpec test failed on C:\Dev\git\FAKE\test\Test.Fake.Deploy.dll, C:\Dev\git\FAKE\test\Test.Fake.Deploy.Web.dll, C:\Dev\git\FAKE\test\Test.Fake.Deploy.Web.File.dll, C:\Dev\git\FAKE\test\Test.FAKECore.dll, C:\Dev\git\FAKE\test\Test.Git.dll.                                                         
   at Microsoft.FSharp.Core.Operators.FailWith[T](String message)             
   at Fake.MSpecHelper.MSpec(FSharpFunc`2 setParams, IEnumerable`1 assemblies)
                                                                              
   at FSI_0001.Build.clo@138-8.Invoke(Unit _arg6) in C:\Dev\git\FAKE\build.fsx:line 139                                                                     
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target)              
```

It says on github that it passes, so it is a little bit weird that it doesn't when I run it locally.

### PR DESCRIPTION
**Pull request by bentayloruk**
Tests invoking csc.exe were failing when paths contained a space.  Updated csc invocation to ensure quote references, output path and input file paths when a space is detected and not already quoted.

Tried to be light touch and backwards compatible.  Not sure how widely used CscHelper is used in the wild.

### CODE REVIEW

File: src/app/FakeLib/CscHelper.fs [hunk 1]
```diff
@@ -78,11 +78,21 @@ let cscExe toolPath (srcFiles : string list) (opts : string list) : int =
 ///                                Target = ...
 ///                                ... })
 let csc (setParams : CscParams -> CscParams) (inputFiles : string list) : int =
-    let inputFiles = inputFiles |> Seq.toList
+    // Helper to quote a path with spaces in it, if not already quoted.  See https://github.com/fsharp/FAKE/issues/992
+    let ensureQuotedPath (path : string) =
+        // Sensitive to being backwards compatible with people that are using
+        // Csc AND quoting their paths.  Only quote if space in path and quotes not detected.
+        // MAYBE this should go in the FileSystemHelper module?
+        if path.Contains(" ") then
```
Comment (bentayloruk) [inline src/app/FakeLib/CscHelper.fs]: Thinking this should probably be trimmed.  Currently we could double quote a path that is already quoted, but book ended with whitespace.

File: src/app/FakeLib/CscHelper.fs [hunk 2]
```diff
@@ -78,11 +78,22 @@ let cscExe toolPath (srcFiles : string list) (opts : string list) : int =
 ///                                Target = ...
 ///                                ... })
 let csc (setParams : CscParams -> CscParams) (inputFiles : string list) : int =
-    let inputFiles = inputFiles |> Seq.toList
+    // Helper to quote a path with spaces in it, if not already quoted.  See https://github.com/fsharp/FAKE/issues/992
+    let ensureTrimQuotedPath (path : string) =
```
Comment (forki) [inline src/app/FakeLib/CscHelper.fs]: Can we put this in one of the other helpers? Maybe we already have something similar

Comment (bentayloruk) [inline src/app/FakeLib/CscHelper.fs]: I could not see a helper for this.  My search for "\"%s\"" yielded a handful of other places doing this.  I will add a helper function `trimAndEnsureQuotedIfRequired` to the `FileSystemHelper.fs`.

Comment (forki) [inline src/app/FakeLib/CscHelper.fs]: Thx.

Comment (bentayloruk) [inline src/app/FakeLib/CscHelper.fs]: Actually, I'm hesitant about making this a general function.  Digging around, this is [not as simple as it first appears](http://blogs.msdn.com/b/twistylittlepassagesallalike/archive/2011/04/23/everyone-quotes-arguments-the-wrong-way.aspx).  Might be better to leave it local to the `csc` function.  It is already local in the other places.

**Comment by forki** [comment]
Thx
